### PR TITLE
Add CPR slash command

### PR DESCRIPTION
**Pull request by TechGeekGamer**
This adds the slash command `/cpr` which links to Team Neptune's [CommonProblemResolver](https://github.com/Team-Neptune/CommonProblemResolver) tool. Intended for use within the [Team Neptune Discord Server](https://discord.gg/Qs5c68dAEG).

### CODE REVIEW

**Comment by hax4dazy** [comment]
Seems fine but maybe you wanna build some documentation on how to run the docker container

**Comment by Slluxx** [comment]
did anyone test performance on native vs docker?
i like docker but not everything needs a container tbh

**Comment by hax4dazy** [comment]
The main reason to put it in a docker container is so I can move it to my other server. It'll make hosting / management a bit easier

**Comment by TechGeekGamer** [comment]
@Slluxx 
> did anyone test performance on native vs docker?

I'll do a bit of testing and report back.
> i like docker but not everything needs a container tbh

True, but it does not hurt to have it as an option either. You're not forced to create a container, it's just there as an option. However like @hax4dazy said, it's mainly for his use to transfer hosting from me to him.

**Comment by TechGeekGamer** [comment]
@Slluxx Did some testing and performance is about the same for me, but you have to take into account that my internet isn't the best in the world either.

**Review by hax4dazy — CHANGES_REQUESTED** [review]
Add info on how to run docker container

**Comment by TechGeekGamer** [comment]
> Add info on how to run docker container

I'll look into that later, however I since this PR is intended only for adding the `/cpr` slash command, I'll work on docker stuff after this PR gets merged/closed.

**Review by hax4dazy — APPROVED** [review]
Seems fine

**Review by Slluxx — APPROVED** [review]
seems fine to me too

**Pull request merged**
